name: "CI"
on:
  push:
    branches-ignore:
      - "production"
      - "docs"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - ".gitignore"
      - "README.md"
      - "LICENSE"
  pull_request:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.0, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Assets
        run: npm i && npm run build

      - name: Test Site
        run: bash tools/test
